// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfnxzwxnuemecadfogbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmbnh6d3hudWVtZWNhZGZvZ2JqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NDc4MzEsImV4cCI6MjA2ODUyMzgzMX0.SeaAv2BwMGliVMPKsCBzyRJEcHYuuRLPKNuROWY0ouw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});